### ISSUE TITLE
supervisord 缺少 `-n` 参数容器直接退出

### ISSUE THREAD

**Issue by XuCcc** [ctfhub-team/base_web_supervisor_python_36#1]
https://github.com/ctfhub-team/base_web_supervisor_python_36/blob/d8c04f177206686ad229c22aa97e6c70f92fc287/_files/docker-entrypoint#L9

`supervisord version: 4.2.0`

```bash
-n/--nodaemon -- run in the foreground (same as 'nodaemon=true' in config file)
```

**Comment by yw9381** [comment]
已修复该问题，最新镜像已推送至DockerHub https://hub.docker.com/r/ctfhub/base_web_supervisor_python_36/tags
并同时提供了example以方便使用 https://github.com/ctfhub-team/base_web_supervisor_python_36/tree/master/example
